export const teamMembers = [
  {
    image: 'jeison',
    nombre: 'Jeison Cifuentes',
    puesto: 'Presidente',
    bio: 'Joven apasionado del sector social y de los negocios queriendo transformar territorios por medio de nuevos proyectos sociales que impacten a las comunidades.',
    bioExtended: 'Uno de nuestros fundadores y representante legal de la fundación. Vela por el cumplimiento de las metas y objetivos dentro de ella, dirigiendo el equipo administrativo.',
    instagram: 'https://instagram.com/jeison_cifuentes_?igshid=YmMyMTA2M2Y=',
    facebook: 'https://www.facebook.com/jeison.cifuentess',
    twitter: 'https://twitter.com/JeisonCifuentez',
  },
  {
    image: 'kevin',
    nombre: 'Kevin Ramirez',
    puesto: 'Vicepresidente',
    bio: 'Llega con su experiencia administrativa a la fundación en el 2020 para aportar, sumar y generar más experiencia en el sector social y comunitario.',
    bioExtended: 'Es el encargado de coordinar que todos los procesos y proyectos estén activos y funcionando adecuadamente para el cumplimiento de metas y objetivos propuestos por la fundación.',
    instagram: '',
    facebook: '',
    twitter: '',
  },
  {
    image: 'andi',
    nombre: 'Andrés Palacio',
    puesto: 'Director Ejecutivo',
    bio: 'Llega a la fundación en el 2018 con muchas ganas de aprender y potenciar su conocimiento con la mejor actitud y disciplina.',
    bioExtended: 'Uno de nuestros líderes cuyo aporte es controlar que todos los procesos tanto legales como administrativos estén en óptimas condiciones.',
    instagram: '',
    facebook: '',
    twitter: '',
  },
  {
    image: 'camila',
    nombre: 'Camila Valencia',
    puesto: 'Secretaria',
    bio: 'La caracteriza su sencillez y su humildad ante la comunidad. Es nuestro apoyo administrativo en la gestión de todos los procesos y proyectos.',
    bioExtended: 'Apoyo administrativo en la gestión de todos los procesos y proyectos de la fundación, lo cual la hace parte importante y ficha clave en sus funciones.',
    instagram: 'https://instagram.com/m.camila.valencia?igshid=YmMyMTA2M2Y=',
    facebook: 'https://www.facebook.com/mcamilavv',
    twitter: 'https://twitter.com/luna971130',
  },
  {
    image: 'velasquez',
    nombre: 'Camila Velasquez',
    puesto: 'Tesorera',
    bio: 'Joven con muy buena actitud, confiable y honesta. Su trabajo la lleva a ser una persona con muchas capacidades en temas contables.',
    bioExtended: 'Vela porque los recursos de la fundación lleven un orden y una buena distribución, que los dineros sean bien administrados y la legalidad de sus movimientos tengan un registro para potenciar la confianza.',
    instagram: 'https://instagram.com/camilavelasquezg_?igshid=YmMyMTA2M2Y=',
    facebook: 'https://www.facebook.com/mariacamila.velasquezgraciano',
    twitter: '',
  },
  {
    image: 'milena',
    nombre: 'Milena Díaz',
    puesto: 'Abogada',
    bio: 'Mujer eficiente, capaz y sencilla. Siempre disponible a cualquier inquietud o problema que tenga algún miembro de la fundación.',
    bioExtended: 'Ficha clave dentro de la fundación ya que es quien presta toda la asesoría legal ante las diferentes entidades gubernamentales y administrativas.',
    instagram: 'https://instagram.com/s_mile.d?igshid=YmMyMTA2M2Y=',
    facebook: 'https://www.facebook.com/milena.diazhenao',
    twitter: '',
  },
];
